export ZSH=/Users/jd/.oh-my-zsh
export MANPATH="/usr/local/man:$MANPATH"
export ARCHFLAGS="-arch x86_64"
export SSH_KEY_PATH="~/.ssh/dsa_id"
export PATH="$HOME/bin:$PATH"
export USER="jd"
export PYTHON=/usr/bin/python2
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$HOME/.exenv/bin:$PATH"
export JAVA_HOME=`/usr/libexec/java_home`
export PATH="$HOME/.exenv/shims/elixir:$PATH"
export EDITOR="emacs"
export PYTHON_CONFIGURE_OPTS="--enable-framework"
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=$HOME/go_home
export PATH=$PATH:$GOPATH/bin
export PATH=/Users/jd/anaconda3/bin:$PATH
