#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off


# Space names
yabai -m space 1 --label dev
yabai -m space 2 --label browser
yabai -m space 3 --label notion
yabai -m space 4 --label social # 



# global settings
yabai -m config                                 \
    insert_feedback_color        0xffd75f5f \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on            \
    top_padding                  4             \
    bottom_padding               4             \
    left_padding                 4             \
    right_padding                4             \
    window_gap                   4             \
    layout                       bsp            \
    mouse_modifier               ctrl             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded.."
